"""
Create or modify Blender animations.

This tool generates a Blender Python script based on a prompt and optional
feedback from previous iterations, then runs Blender in headless mode to
create the animation.
"""

import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class AnimationResult:
    """Result of animation creation."""

    blend_file: Path
    success: bool
    message: str
    script_used: str  # The Blender Python script that was generated


# Template for Blender animation script
BLENDER_SCRIPT_TEMPLATE = '''"""
Auto-generated Blender animation script.
Prompt: {prompt}
Iteration feedback: {feedback}
"""

import bpy
import math

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

# Animation settings
fps = {fps}
duration_seconds = {duration}
total_frames = fps * duration_seconds

bpy.context.scene.frame_start = 1
bpy.context.scene.frame_end = total_frames
bpy.context.scene.render.fps = fps

{animation_code}

# Save the file
bpy.ops.wm.save_as_mainfile(filepath="{output_path}")
print("Animation saved to: {output_path}")
'''


def create_animation(
    prompt: str,
    output_path: Path | str,
    feedback: list[str] | None = None,
    animation_code: str | None = None,
    fps: int = 30,
    duration: float = 2.0,
) -> AnimationResult:
    """
    Create a Blender animation from a prompt.

    Args:
        prompt: Description of the animation to create
        output_path: Where to save the .blend file
        feedback: Optional list of suggestions from previous analysis
        animation_code: Optional pre-written Blender Python code for animation
        fps: Frames per second
        duration: Animation duration in seconds

    Returns:
        AnimationResult with the path to the created .blend file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Format feedback for the script
    feedback_str = "None"
    if feedback:
        feedback_str = "\\n".join(f"- {f}" for f in feedback)

    # Use provided animation code or generate a placeholder
    if animation_code is None:
        animation_code = _generate_placeholder_animation(prompt)

    # Generate the Blender script
    script_content = BLENDER_SCRIPT_TEMPLATE.format(
        prompt=prompt.replace('"', '\\"'),
        feedback=feedback_str.replace('"', '\\"'),
        fps=fps,
        duration=int(duration),
        animation_code=animation_code,
        output_path=str(output_path).replace("\\", "/"),
    )

    # Write script to temp file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        f.write(script_content)
        script_path = f.name

    try:
        # Run Blender in headless mode
        result = subprocess.run(
            ["blender", "--background", "--python", script_path],
            capture_output=True,
            text=True,
            timeout=120,
        )

        if result.returncode != 0:
            return AnimationResult(
                blend_file=output_path,
                success=False,
                message=f"Blender failed: {result.stderr}",
                script_used=script_content,
            )

        if not output_path.exists():
            return AnimationResult(
                blend_file=output_path,
                success=False,
                message="Blender completed but no file was created",
                script_used=script_content,
            )

        return AnimationResult(
            blend_file=output_path,
            success=True,
            message=f"Animation created: {output_path}",
            script_used=script_content,
        )

    except subprocess.TimeoutExpired:
        return AnimationResult(
            blend_file=output_path,
            success=False,
            message="Blender timed out after 120 seconds",
            script_used=script_content,
        )
    finally:
        # Clean up temp script
        Path(script_path).unlink(missing_ok=True)


def _generate_placeholder_animation(prompt: str) -> str:
    """
    Generate placeholder animation code.

    In production, this would be replaced by Claude generating the actual
    animation code based on the prompt and Gemini feedback.
    """
    return '''
# Placeholder animation - this should be replaced with actual animation code
# generated by Claude based on the prompt and Gemini feedback

# Create a simple cube as placeholder
bpy.ops.mesh.primitive_cube_add(size=2, location=(0, 0, 1))
cube = bpy.context.active_object
cube.name = "Placeholder"

# Simple bounce animation
for frame in range(1, total_frames + 1):
    bpy.context.scene.frame_set(frame)
    t = frame / total_frames
    z = 1 + abs(math.sin(t * math.pi * 4)) * 2
    cube.location = (0, 0, z)
    cube.keyframe_insert(data_path="location", frame=frame)

print("Placeholder animation created - replace with actual animation code")
'''


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage: python -m animation_tools.create_animation <output.blend> <prompt>")
        sys.exit(1)

    output = Path(sys.argv[1])
    prompt = sys.argv[2]

    print(f"Creating animation: {prompt}")
    result = create_animation(prompt, output)

    print(f"\nSuccess: {result.success}")
    print(f"Message: {result.message}")
    if result.success:
        print(f"File: {result.blend_file}")
